---
- name: perform versionscheck
  ansible.builtin.include_tasks: versioncheck.yml
  when: submodules_versioncheck|bool

- name: Create (common) web root parent for sites
  ansible.builtin.file:
    path: '{{ site.webroot.path | default(default_webroot_prefix + site.name) }}/..'
    state: directory
    owner: '{{ default_webroot_user }}'
    group: '{{ default_webroot_group }}'
    mode: 'u=rwx,g=rx,o=rx'
  with_items: '{{ nginx_sites }}'
  loop_control:
    loop_var: site
  when: site.webroot | default(false)

- name: Create web root for sites
  ansible.builtin.file:
    path: '{{ site.webroot.path | default(default_webroot_prefix + site.name) }}'
    state: directory
    owner: '{{ site.webroot.user | default(default_webroot_user) }}'
    group: '{{ site.webroot.group | default(default_webroot_group) }}'
    mode: '{{ site.webroot.mode | default(default_webroot_mode) }}'
  with_items: '{{ nginx_sites }}'
  loop_control:
    loop_var: site
  when: site.webroot | default(false)
