---
#- name: Create default common path prefix for sites
#  file:
#    path: '{{ default_webroot_prefix }}'
#    state: directory
#    owner: '{{ default_webroot_user }}'
#    group: '{{ default_webroot_group }}'
#    mode: '{{ default_webroot_mode }}'
#  tags:
#    - configuration


- name: Create (common) web root parent for sites
  file:
    path: '{{ site.webroot.path | default(default_webroot_prefix + site.name) }}/..'
    state: directory
    owner: '{{ default_webroot_user }}'
    group: '{{ default_webroot_group }}'
    mode: '{{ default_webroot_mode }}'
  with_items: '{{ nginx_sites }}'
  loop_control:
    loop_var: site
  when: site.webroot | default(false)
  tags:
    - configuration


- name: Create web root for sites
  file:
    path: '{{ site.webroot.path | default(default_webroot_prefix + site.name) }}'
    state: directory
    owner: '{{ site.webroot.user | default(default_webroot_user) }}'
    group: '{{ site.webroot.group | default(default_webroot_group) }}'
    mode: '{{ site.webroot.mode | default(default_webroot_mode) }}'
  with_items: '{{ nginx_sites }}'
  loop_control:
    loop_var: site
  when: site.webroot | default(false)
  tags:
    - configuration
